server:
  port: 8086

spring:
  application:
    name: certification-badge-management-service
  datasource:
    url: jdbc:mysql://localhost:3306/learnvault_cbm?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


jwt:
  secret: learnvault-secret-key-2026-batch11-pod2-identity-access-management-service